# Generated by Django 3.1.2 on 2020-10-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactPersonName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=400)),
                ('Source', models.CharField(max_length=50)),
                ('CurrentStage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfFollowup', models.DateField()),
                ('Response', models.CharField(max_length=100)),
                ('Lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info.lead')),
            ],
        ),
    ]
